In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('length .csv')

In [3]:

dataset

date location  age        disease sevearity_of_the_disease  \
0    06-04-2012    India   42    heartstroke                     high   
1    07-05-2012    India   41         cancer                      low   
2    09-01-2012    India   42    heartstroke                 moderate   
3    05-11-2012    India   39         cancer                      low   
4    06-04-2012    India   43         cancer                      low   
5    07-05-2012    India   44  bone fracture                     high   
6    09-01-2012    India   50  bone fracture                 moderate   
7    05-11-2012    India   29          fever                     high   
8    09-01-2012    India   44          fever                     high   
9    09-01-2012    India   27    heartstroke                 moderate   
10   09-01-2012    India   31         cancer                     high   
11   09-01-2012    India   24  bone fracture                      low   
12   09-01-2012    India   34    heartstroke                 moderate   
13   09-01-2012    India   25         cancer                 moderate   
14   09-01-2012    India    8          fever                      low   
15   06-04-2012    India   45          fever                     high   
16   06-04-2012    India   58         cancer                 moderate   
17   06-04-2012    India   24         cancer                      low   
18   06-04-2012    India   45  bone fracture                     high   
19   06-04-2012    India   24  bone fracture                      low   
20   06-04-2012    India   41         cancer                 moderate   
21   06-04-2012    India   32          astma                      low   
22   06-04-2012    India   38         cancer                      low   
23   06-04-2012    India   46         cancer                     high   
24   06-04-2012    India   38  bone fracture                 moderate   
25   06-04-2012    India   25  bone fracture                     high   
26    8/29/2012    India   36          fever                     high   
27    5/26/2012    India   44          fever                 moderate   
28    9/22/2012    India   43          fever                     high   
29   08-09-2012    India   29    heartstroke                      low   
..          ...      ...  ...            ...                      ...   
469   3/26/2012    India    8          fever                     high   
470  08-07-2012    India   27    heartstroke                 moderate   
471  12-02-2012    India   37         cancer                      low   
472   2/27/2012    India   26  bone fracture                      low   
473   6/20/2012    India   28    heartstroke                     high   
474   9/18/2012    India   33         cancer                 moderate   
475  08-05-2012    India   46          fever                     high   
476  12/18/2012    India   31          fever                     high   
477  09-02-2012    India   40         cancer                 moderate   
478   9/28/2012    India   38         cancer                     high   
479  07-03-2012    India   29  bone fracture                      low   
480  11-11-2012    India   34  bone fracture                 moderate   
481   9/25/2012    India   23         cancer                 moderate   
482  09-01-2012    India   37          astma                      low   
483  11/18/2012    India   37         cancer                     high   
484   7/18/2012    India   61         cancer                 moderate   
485   5/16/2012    India    8  bone fracture                      low   
486  11/19/2012    India   37  bone fracture                     high   
487  12/26/2012    India   39          fever                      low   
488  11-02-2012    India   30          fever                 moderate   
489  02-05-2012    India   55          fever                      low   
490  02-05-2012    India   29    heartstroke                      low   
491  02-05-2012    India   41         cancer                     high

In [4]:
dataset.isnull().any()

date                        False
location                    False
age                         False
disease                     False
sevearity_of_the_disease    False
frequency_of_suffering      False
pulse                       False
duration_of_suffering       False
length_of_stay              False
dtype: bool

In [5]:
dataset.corr()

age     pulse  duration_of_suffering  \
age                    1.000000  0.090659               0.032344   
pulse                  0.090659  1.000000               0.000387   
duration_of_suffering  0.032344  0.000387               1.000000   
length_of_stay        -0.055600  0.031010               0.019173   

                       length_of_stay  
age                         -0.055600  
pulse                        0.031010  
duration_of_suffering        0.019173  
length_of_stay               1.000000

In [6]:
data=dataset.iloc[:,2:]

In [7]:
data

age        disease sevearity_of_the_disease frequency_of_suffering  \
0     42    heartstroke                     high                regural   
1     41         cancer                      low              irregular   
2     42    heartstroke                 moderate              irregular   
3     39         cancer                      low              irregular   
4     43         cancer                      low                regular   
5     44  bone fracture                     high              irregular   
6     50  bone fracture                 moderate              irregular   
7     29          fever                     high                regular   
8     44          fever                     high                regular   
9     27    heartstroke                 moderate              irregular   
10    31         cancer                     high                regular   
11    24  bone fracture                      low              irregular   
12    34    heartstroke                 moderate              irregular   
13    25         cancer                 moderate              irregular   
14     8          fever                      low                regular   
15    45          fever                     high              irregular   
16    58         cancer                 moderate                regular   
17    24         cancer                      low              irregular   
18    45  bone fracture                     high                regular   
19    24  bone fracture                      low                regular   
20    41         cancer                 moderate              irregular   
21    32          astma                      low              irregular   
22    38         cancer                      low              irregular   
23    46         cancer                     high              irregular   
24    38  bone fracture                 moderate                regular   
25    25  bone fracture                     high                regular   
26    36          fever                     high              irregular   
27    44          fever                 moderate              irregular   
28    43          fever                     high                regular   
29    29    heartstroke                      low              irregular   
..   ...            ...                      ...                    ...   
469    8          fever                     high              irregular   
470   27    heartstroke                 moderate                regular   
471   37         cancer                      low                regular   
472   26  bone fracture                      low                regular   
473   28    heartstroke                     high                regular   
474   33         cancer                 moderate                regular   
475   46          fever                     high                regular   
476   31          fever                     high              irregular   
477   40         cancer                 moderate              irregular   
478   38         cancer                     high                regular   
479   29  bone fracture                      low                regular   
480   34  bone fracture                 moderate              irregular   
481   23         cancer                 moderate                regular   
482   37          astma                      low                regular   
483   37         cancer                     high              irregular   
484   61         cancer                 moderate                regular   
485    8  bone fracture                      low              irregular   
486   37  bone fracture                     high                regular   
487   39          fever                      low                regular   
488   30          fever                 moderate              irregular   
489   55          fever                      low              irregular   
490   29    heartstroke       

In [8]:
x=data.iloc[:,0:6]
x

age        disease sevearity_of_the_disease frequency_of_suffering  \
0     42    heartstroke                     high                regural   
1     41         cancer                      low              irregular   
2     42    heartstroke                 moderate              irregular   
3     39         cancer                      low              irregular   
4     43         cancer                      low                regular   
5     44  bone fracture                     high              irregular   
6     50  bone fracture                 moderate              irregular   
7     29          fever                     high                regular   
8     44          fever                     high                regular   
9     27    heartstroke                 moderate              irregular   
10    31         cancer                     high                regular   
11    24  bone fracture                      low              irregular   
12    34    heartstroke                 moderate              irregular   
13    25         cancer                 moderate              irregular   
14     8          fever                      low                regular   
15    45          fever                     high              irregular   
16    58         cancer                 moderate                regular   
17    24         cancer                      low              irregular   
18    45  bone fracture                     high                regular   
19    24  bone fracture                      low                regular   
20    41         cancer                 moderate              irregular   
21    32          astma                      low              irregular   
22    38         cancer                      low              irregular   
23    46         cancer                     high              irregular   
24    38  bone fracture                 moderate                regular   
25    25  bone fracture                     high                regular   
26    36          fever                     high              irregular   
27    44          fever                 moderate              irregular   
28    43          fever                     high                regular   
29    29    heartstroke                      low              irregular   
..   ...            ...                      ...                    ...   
469    8          fever                     high              irregular   
470   27    heartstroke                 moderate                regular   
471   37         cancer                      low                regular   
472   26  bone fracture                      low                regular   
473   28    heartstroke                     high                regular   
474   33         cancer                 moderate                regular   
475   46          fever                     high                regular   
476   31          fever                     high              irregular   
477   40         cancer                 moderate              irregular   
478   38         cancer                     high                regular   
479   29  bone fracture                      low                regular   
480   34  bone fracture                 moderate              irregular   
481   23         cancer                 moderate                regular   
482   37          astma                      low                regular   
483   37         cancer                     high              irregular   
484   61         cancer                 moderate                regular   
485    8  bone fracture                      low              irregular   
486   37  bone fracture                     high                regular   
487   39          fever                      low                regular   
488   30          fever                 moderate              irregular   
489   55          fever                      low              irregular   
490   29    heartstroke       

In [9]:
x=data.iloc[:,0:6].values
x

array([[42, 'heartstroke', 'high', 'regural', 96, 6],
       [41, 'cancer', 'low', 'irregular', 61, 2],
       [42, 'heartstroke', 'moderate', 'irregular', 64, 4],
       ...,
       [32, 'bone fracture', 'high', 'regular', 68, 6],
       [40, 'fever', 'low', 'irregular', 61, 2],
       [26, 'fever', 'moderate', 'irregular', 70, 6]], dtype=object)

In [10]:
y=data.iloc[:,6:]

In [11]:
y

length_of_stay
0                 3
1                 2
2                 1
3                 5
4                 2
5                 7
6                 3
7                 3
8                10
9                 2
10                8
11                3
12                6
13                9
14                6
15               30
16                7
17               10
18                4
19               11
20               14
21               12
22                4
23                9
24                6
25               12
26               11
27                2
28                1
29                5
..              ...
469               4
470               9
471               6
472              12
473              11
474               2
475               1
476               5
477               2
478              15
479               3
480               3
481              10
482               5
483               2
484               1
485               5
486               2
487              15
488               3
489               3
490              10
491               2
492               8
493               3
494               6
495               9
496               6
497              30
498               7

[499 rows x 1 columns]

In [12]:
y=data.iloc[:,6:].values

In [13]:
y

array([[ 3],
       [ 2],
       [ 1],
       [ 5],
       [ 2],
       [ 7],
       [ 3],
       [ 3],
       [10],
       [ 2],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [ 6],
       [30],
       [ 7],
       [10],
       [ 4],
       [11],
       [14],
       [12],
       [ 4],
       [ 9],
       [ 6],
       [12],
       [11],
       [ 2],
       [ 1],
       [ 5],
       [ 2],
       [15],
       [ 3],
       [ 3],
       [10],
       [ 2],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [ 6],
       [30],
       [ 7],
       [10],
       [ 4],
       [11],
       [14],
       [12],
       [ 4],
       [ 9],
       [ 6],
       [12],
       [11],
       [ 2],
       [ 1],
       [ 5],
       [ 2],
       [15],
       [ 3],
       [ 3],
       [10],
       [ 2],
       [ 1],
       [ 5],
       [ 2],
       [15],
       [ 3],
       [ 3],
       [10],
       [ 2],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [ 6],
       [30],
       [ 7],

In [14]:

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [15]:
x[:,1]=lb.fit_transform(x[:,1])
x

array([[42, 4, 'high', 'regural', 96, 6],
       [41, 2, 'low', 'irregular', 61, 2],
       [42, 4, 'moderate', 'irregular', 64, 4],
       ...,
       [32, 1, 'high', 'regular', 68, 6],
       [40, 3, 'low', 'irregular', 61, 2],
       [26, 3, 'moderate', 'irregular', 70, 6]], dtype=object)

In [16]:
x[:,2]=lb.fit_transform(x[:,2])
x

array([[42, 4, 0, 'regural', 96, 6],
       [41, 2, 1, 'irregular', 61, 2],
       [42, 4, 2, 'irregular', 64, 4],
       ...,
       [32, 1, 0, 'regular', 68, 6],
       [40, 3, 1, 'irregular', 61, 2],
       [26, 3, 2, 'irregular', 70, 6]], dtype=object)

In [17]:
x[:,3]=lb.fit_transform(x[:,3])
x

array([[42, 4, 0, 2, 96, 6],
       [41, 2, 1, 0, 61, 2],
       [42, 4, 2, 0, 64, 4],
       ...,
       [32, 1, 0, 1, 68, 6],
       [40, 3, 1, 0, 61, 2],
       [26, 3, 2, 0, 70, 6]], dtype=object)

In [18]:
x.shape

(499, 6)

In [19]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categorical_features=[1])
x=oh.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [20]:
x

array([[ 0.,  0.,  0., ...,  2., 96.,  6.],
       [ 0.,  0.,  1., ...,  0., 61.,  2.],
       [ 0.,  0.,  0., ...,  0., 64.,  4.],
       ...,
       [ 0.,  1.,  0., ...,  1., 68.,  6.],
       [ 0.,  0.,  0., ...,  0., 61.,  2.],
       [ 0.,  0.,  0., ...,  0., 70.,  6.]])

In [21]:
x=x[:,1:]
x

array([[ 0.,  0.,  0., ...,  2., 96.,  6.],
       [ 0.,  1.,  0., ...,  0., 61.,  2.],
       [ 0.,  0.,  0., ...,  0., 64.,  4.],
       ...,
       [ 1.,  0.,  0., ...,  1., 68.,  6.],
       [ 0.,  0.,  1., ...,  0., 61.,  2.],
       [ 0.,  0.,  1., ...,  0., 70.,  6.]])

In [22]:
data.head()

age      disease sevearity_of_the_disease frequency_of_suffering  pulse  \
0   42  heartstroke                     high                regural     96   
1   41       cancer                      low              irregular     61   
2   42  heartstroke                 moderate              irregular     64   
3   39       cancer                      low              irregular     76   
4   43       cancer                      low                regular     67   

   duration_of_suffering  length_of_stay  
0                      6               3  
1                      2               2  
2                      4               1  
3                      2               5  
4                      2               2

In [23]:
x.shape

(499, 9)

In [24]:
oh=OneHotEncoder(categorical_features=[5])
x=oh.fit_transform(x).toarray()
x

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[ 1.,  0.,  0., ...,  2., 96.,  6.],
       [ 0.,  1.,  0., ...,  0., 61.,  2.],
       [ 0.,  0.,  1., ...,  0., 64.,  4.],
       ...,
       [ 1.,  0.,  0., ...,  1., 68.,  6.],
       [ 0.,  1.,  0., ...,  0., 61.,  2.],
       [ 0.,  0.,  1., ...,  0., 70.,  6.]])

In [25]:
x=x[:,1:]
x

array([[ 0.,  0.,  0., ...,  2., 96.,  6.],
       [ 1.,  0.,  0., ...,  0., 61.,  2.],
       [ 0.,  1.,  0., ...,  0., 64.,  4.],
       ...,
       [ 0.,  0.,  1., ...,  1., 68.,  6.],
       [ 1.,  0.,  0., ...,  0., 61.,  2.],
       [ 0.,  1.,  0., ...,  0., 70.,  6.]])

In [26]:
x.shape

(499, 10)

In [27]:
oh=OneHotEncoder(categorical_features=[7])
x=oh.fit_transform(x).toarray()
x

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[ 0.,  0.,  1., ..., 42., 96.,  6.],
       [ 1.,  0.,  0., ..., 41., 61.,  2.],
       [ 1.,  0.,  0., ..., 42., 64.,  4.],
       ...,
       [ 0.,  1.,  0., ..., 32., 68.,  6.],
       [ 1.,  0.,  0., ..., 40., 61.,  2.],
       [ 1.,  0.,  0., ..., 26., 70.,  6.]])

In [28]:
x=x[:,1:]
x

array([[ 0.,  1.,  0., ..., 42., 96.,  6.],
       [ 0.,  0.,  1., ..., 41., 61.,  2.],
       [ 0.,  0.,  0., ..., 42., 64.,  4.],
       ...,
       [ 1.,  0.,  0., ..., 32., 68.,  6.],
       [ 0.,  0.,  1., ..., 40., 61.,  2.],
       [ 0.,  0.,  0., ..., 26., 70.,  6.]])

In [29]:
x.shape

(499, 11)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [32]:
x_train

array([[ 0.,  0.,  1., ..., 36., 64.,  2.],
       [ 1.,  0.,  1., ..., 40., 77.,  2.],
       [ 1.,  0.,  1., ..., 29., 88.,  2.],
       ...,
       [ 0.,  0.,  0., ..., 41., 71.,  6.],
       [ 0.,  0.,  1., ..., 39., 73.,  2.],
       [ 1.,  0.,  1., ..., 44., 95.,  2.]])

In [33]:
y_train

array([[12],
       [ 3],
       [ 3],
       [11],
       [ 3],
       [ 6],
       [ 2],
       [ 2],
       [ 3],
       [ 2],
       [15],
       [ 3],
       [10],
       [10],
       [ 2],
       [30],
       [ 3],
       [10],
       [ 2],
       [10],
       [10],
       [ 9],
       [ 6],
       [ 5],
       [ 8],
       [ 3],
       [ 3],
       [ 4],
       [ 5],
       [ 9],
       [ 1],
       [ 9],
       [ 2],
       [ 5],
       [11],
       [ 3],
       [ 8],
       [ 2],
       [ 2],
       [ 3],
       [ 6],
       [11],
       [ 6],
       [11],
       [15],
       [ 2],
       [10],
       [ 5],
       [ 2],
       [ 7],
       [12],
       [12],
       [30],
       [ 8],
       [ 1],
       [ 4],
       [10],
       [14],
       [ 9],
       [ 6],
       [ 3],
       [11],
       [ 2],
       [11],
       [12],
       [12],
       [ 1],
       [ 2],
       [ 7],
       [ 9],
       [ 3],
       [ 6],
       [ 2],
       [ 1],
       [ 9],
       [11],
       [ 4],

In [34]:
x_test

array([[ 1.,  0.,  0., ..., 44., 67.,  6.],
       [ 1.,  0.,  0., ..., 28., 96.,  4.],
       [ 0.,  0.,  0., ..., 42., 85.,  4.],
       ...,
       [ 1.,  0.,  0., ..., 42., 60.,  6.],
       [ 0.,  0.,  0., ...,  8., 66.,  4.],
       [ 1.,  0.,  0., ..., 45., 70.,  6.]])

In [35]:
x.shape

(499, 11)

In [36]:
from sklearn.linear_model import LinearRegression
mr=LinearRegression()

In [37]:
mr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [38]:
y_predict=mr.predict(x_test)

In [39]:
y_predict

array([[7.35168894],
       [7.95920201],
       [6.79478758],
       [6.2716665 ],
       [6.88583592],
       [6.69107551],
       [7.42051119],
       [6.79608389],
       [7.39853399],
       [6.7244195 ],
       [7.46761142],
       [6.93169802],
       [7.23882461],
       [8.07864977],
       [8.26445038],
       [8.83098112],
       [6.90458709],
       [7.23407049],
       [7.89988116],
       [7.33073146],
       [8.13477546],
       [6.72772717],
       [7.01900291],
       [8.19208165],
       [7.34245608],
       [8.65168879],
       [6.89290428],
       [7.14777627],
       [6.86345768],
       [7.98337787],
       [5.9695862 ],
       [7.31955412],
       [8.58432131],
       [6.48194924],
       [7.19262772],
       [7.05536813],
       [8.29407751],
       [7.70086027],
       [7.63962204],
       [7.64950305],
       [6.88604627],
       [7.62462792],
       [6.91992051],
       [8.15113488],
       [6.89618246],
       [6.94085834],
       [7.62702985],
       [8.700

In [40]:
y_test

array([[ 2],
       [ 9],
       [ 7],
       [ 9],
       [ 2],
       [30],
       [30],
       [ 3],
       [ 9],
       [ 3],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [12],
       [ 2],
       [14],
       [ 2],
       [10],
       [ 3],
       [12],
       [ 2],
       [10],
       [ 4],
       [11],
       [ 7],
       [12],
       [15],
       [ 8],
       [ 2],
       [11],
       [ 3],
       [ 2],
       [ 3],
       [15],
       [15],
       [ 8],
       [ 6],
       [12],
       [ 3],
       [12],
       [14],
       [30],
       [30],
       [ 7],
       [ 2],
       [ 3],
       [ 6],
       [ 2],
       [ 7],
       [ 2],
       [ 6],
       [30],
       [ 6],
       [ 6],
       [ 6],
       [11],
       [ 2],
       [ 4],
       [ 2],
       [ 4],
       [ 2],
       [12],
       [ 5],
       [10],
       [ 7],
       [ 8],
       [ 7],
       [ 2],
       [30],
       [ 4],
       [15],
       [ 6],
       [15],
       [ 5],
       [10],
       [ 9],

In [41]:
y_pred=mr.predict(x_test)

In [42]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-0.01765100008165721

In [43]:
x_train.shape

(399, 11)